name: Build Java Project  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      - uses: actions/setup-java@v1  
        with:  
          java-version: "11"  
      - run: mvn clean package -Dmaven.test.skip=true
